version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.1-node-browsers
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-

      - run: npm install -g karma karma-cli karma-chrome-launcher karma-cljs-test

      - run: lein test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
